name: Publish
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment: secrets
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Login
      run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
    - name: Publish
      run: |-
          cargo publish \
            --workspace \
            --all-features \
            --allow-dirty \
            --no-confirm \
            --no-verify \
