name: Rust

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Login
      run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
    - name: Publish
      run: |-
          cargo release \
            publish \
            --workspace \
            --all-features \
            --allow-branch HEAD \
            --no-confirm \
            --no-verify \
            --execute
